spring:
  datasource:
    url: "jdbc:postgresql://localhost/postgres"
    username: postgres
  cloud:
    stream:
      bindings:
        output:
          destination: "valkey-cdc"
cdc:
  source:
    jdbc:
      lastRowIdWherePosition: 1
      lastTimestampWherePosition: 2
      sqlSqlWhereClause:
        where CAST (id AS INTEGER) > CAST (? AS INTEGER) or order_date >= ?
      cdcId: postgresToValKey
      sqlSelectWithFrom:
        select id, order_date, purchaser, quantity, product_id 
        from inventory.orders
      lastRowIdSelectColumnName: id
      lastTimestampSelectColumnName: order_date
    schedule:
      cron: "*/10 * * * * *"