server:
  port: 8064
spring:
  application:
    name: stream-source
  cloud:
    function:
      definition: publish;
      http:
        POST: publish
      web:
        path: /functions
valkey:
  stream:
    name: stream